$$ &&
	$$('lik', {
		xprefix: 'https://xaidozy.github.io/lik',
		data: [
			'Yo^Color_Code_F;フェルト',
			'Clan3yang0yang0;Taylor Swift;Y^懒羊羊',
			'Cping2fan2zhi1lu4;朴树;平凡之路',
			'Juice_World',
			'a^ONE_PUNCH_KO',
			'a^Climb_Ka',
			'R^A',
			'go^Others_i_World',
			'The_Nights_Ever_Fading;DInxm Robinson',
			'a^I_Walk_This_Earth_All_By_Myself;EKKSTACY',
			'a^A4KEY',
			'Lava_Drinker',
			'Cxi3huan1he2ni3de1xia4tian1;;p^喜欢和你的夏天',
			'Y^Fatal_Love;Jori King',
			'p^POLICMR_LKW_SERGEAN',
			'Cxia4ge4lu4kou3zai4jian4ba1;;p^下个路口再见吧',
			'Cai4zai4xi1yuan2qian2;;Y^爱在西元前',
			'Ao^Midwest',
			'R^U',
			'No_worries;Pogo',
			'po^Toosii',
			'ro^Rage_Nin;Rotte',
			'ao^Chilol;Since yo',
			'go^Other_Side;Lena Raine',
			'po^Slayer;Misterk',
			'io^Is_It_Just_Me;Sasha Alex Sloan',
			'a^vinsoca;Loov',
			'p^Ru1',
			'jp56;;Y^君がくれたもの~',
			'g^Mystic_Tides;FEWZ',
			'Lake_Arrowhead;Dunn',
			'Sad;;g^Sad(Instrumental)',
			'SAD2;Lil Poke;y^SAD(Demo)',
			'p^Fractures;Luavec',
			'a^SASIOVERLXRD',
			'p^Lanovera',
			'g^50000',
			'Lofi_Chill_X3',
			'Astroy',
			'Post_Malone',
			'g^Fly_me_to_the_Moon',
			'Evening_WindMill;Lofi',
			'g^Before_we_Die;Lofi',
			'a^Lady',
			'p^bossed_up;calebcruise',
			'Help',
			'a^J_Cole_x_Kendrick_Lamar_x_Kanye',
			'Wegonebeok_x_Nettspend_x_Osamason',
			'a^Hyperpop_x_lil_uzi_vert_x_Y2K',
			'p^varJ7U6v',
		],
	});
